### PR TITLE
Interrupt subprocesses first and wait if they exit

### PR DESCRIPTION
**Pull request by ghost**
If the subprocesses are killed directly they might
not be able to clean up. Which can change the result
and may cause orphan sub-subprocesses.
- Per default python only does cleanup on SIGINT not
  SIGTERM nor SIGKILL (impossible). Not even with atexit. 
  We would have to catch SIGTERM manually. Therefore I decided
  to send SIGINT then SIGKILL
- Since we send SIGINT we get trace-backs on stderr,
  therefore stderr is sent to DEVNULL too

### CODE REVIEW

**Comment by ghost** [comment]
This patch seems to work, but I want to finish a test-run first. I let you know when it is finished.

**Comment by ghost** [comment]
@DRMacIver Successfully tested with 3.4.4 and 3.5.1. Please check the patch again. I changed the first signal from SIGTERM to SIGINT, because it is more suitable for writing python wrappers that classify results and return appropriate exit codes.

**Comment by DRMacIver** [comment]
This looks reasonable to me and I'm happy to merge it, but I've realised a glitch.

The glitch is that this software is currently unlicensed and I want to be free to relicense it later. This makes accepting patches I can't relicense dicey. But, um, CLAs are bullshit.

So, what I'm going to do is add a LICENCE file that basically says that the following contributors retain copyright over their patches to this repository but have agreed to license it under the MIT license and ask you to add your name to the list as part of this PR. Does that sound OK by you?

**Comment by DRMacIver** [comment]
(I'll put the whole thing under GPLv3 at the same time but will probably change that later)

**Comment by ghost** [comment]
@DRMacIver  I am also ok with signing over the copyright to you, so you can do with it what you want. I can send you a GPG signed email, if that is enough?

**Comment by DRMacIver** [comment]
That would be perfect, thanks. :-)

**Comment by DRMacIver** [comment]
Sorry, this is a stupid thing to have to care about but reasons.

**Comment by ghost** [comment]
I would do the same. I sent the email, as far as I can tell mutt did everything allright.

**Pull request merged**
